### ISSUE TITLE
Make servers on Modrinth App

### ISSUE THREAD

**Issue by StudiCraft** [modrinth/code#2873] opened 2024-10-31 13:13 UTC
### Please confirm the following.

- [x] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate feature requests
- [x] I have checked that this feature request is not on our [roadmap](https://roadmap.modrinth.com)

### What parts of Modrinth is your feature request related too?

App

### Is your suggested feature related to a problem? Please describe.

It could be cool if we would be able to create servers using the Modrinth App. Like ATLauncher does.

**Comment by Erb3** [comment] 2024-11-03 16:19
Duplicate of #2157 
Duplicate of #1239
Duplicate of #779

**Closed** 2024-11-03 16:21 UTC
