### ISSUE TITLE
The CLI Tool doesn't compile

### ISSUE THREAD

**Issue by jorolf** [modrinth/code#1050] opened 2024-02-16 21:51 UTC
### Describe the bug

The `theseus-cli` crate doesn't compile because the *optional* dependency `tauri` for `theseus` isn't optional:

https://github.com/modrinth/theseus/blob/3ff0ff238a4360960a8fee26d45094f92c8fefc5/theseus/Cargo.toml#L44

https://github.com/modrinth/theseus/blob/3ff0ff238a4360960a8fee26d45094f92c8fefc5/theseus/src/util/io.rs#L5-L8

Which has been changed in https://github.com/modrinth/theseus/commit/0d3f007dd4ab5b2fb6dadb09f073c28095b33e33

The compile error I got was:
```
error[E0433]: failed to resolve: use of undeclared crate or module `tauri`
 --> theseus/src/util/io.rs:7:5
  |
7 | use tauri::async_runtime::spawn_blocking;
  |     ^^^^^ use of undeclared crate or module `tauri`

For more information about this error, try `rustc --explain E0433`.
```

### Steps to reproduce

I tried to install the CLI by running
```
cargo install --git https://github.com/modrinth/theseus/ theseus_cli
```

### Expected behavior

The CLI should compile

### System information

N/A

### Additional context

Is the CLI even supported anymore? The change was done over a month ago and nobody noticed?

What is the recommended way to manage the modpack of a headless minecraft server? (Would that even be possible with the CLI?)

**Comment by thiccchris** [comment] 2024-02-21 20:06
### Bug
I have the same issue when I clone the repo as of (2/21/2024)
I cd ./theseus/theseus_cli and cargo build it and it gives the exact error described above 


### Bug 2 (related)
When building the main repo I get this bug

```
error: proc macro panicked
   --> theseus_gui/src-tauri/src/main.rs:152:14
    |
152 |         .run(tauri::generate_context!())
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: message: The `distDir` configuration is set to `"../dist"` but this path doesn't exist

error: could not compile `theseus_gui` (bin "theseus_gui") due to 1 previous error

```
-When I looked at the repo on my main computer with windows vscode I see the same error with the linter extension recommended by the repo .vscode.
-Tried building it on windows too and same error

side note: tauri is set to 1.2 when the latest stable is 1.6

### Specs
```Linux  6.1.0-18-amd64  Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux``` (CLI)
```IBM x3650 m3``` (SSH)


As someone who likes to have linux without a desktop enviroment or window manger, just cli, I would love to see more put into the cli so I could run headless dedicated minecraft servers straight download and managed/updated with modrinth

Thanks, (Hours spent trying to debug all this and get a build of 'theseus_cli': 7 Hours)(It's late now)(I'm tired)
(edit: I posted this to the wrong issue because I thought it was this one so I deleted that one and reposting it here but now this comment is a day old 2/20/2024)

**Comment by thiccchris** [comment] 2024-02-21 20:18
### Found the issue and a quick solution for `Bug 2`
Create a directory called `dist` in `./theseus/theseus_gui`
-apparently this directory is .gitignored somewheer but I can't find it and there is probably a reason why.

### As for `Bug 1`
You need `theseus/theseus/` in order to build `theseus/theseus_cli`
-I don't know how to use ```cargo install --git`` to use the cargo.toml in the main directory where it builds out all the listed binaries so for now clone the repo and run ```cargo build ``` in the main directory after making that directory I talked about in `bug 1`.

side note: once you make that dist directory in the correct place and build in the correct place, you will find the theseus_cli binary in the `target/debug` directory. And it is clearly still a work and progress. If I was any better with rust and github actions I would love to contribute to the cli project. My favorite passtime is running personal custom minecraft modded servers on my own hardware with linux terminal only.

Thanks again, (Hours spent: 3)(Have fun)

**Comment by KnifesmithCode** [comment] 2024-03-26 18:15
### For Bug 1:
It looks like `theseus/theseus_cli` depends on Tauri, which is not part of its listed dependencies.  https://github.com/modrinth/theseus/blob/3ff0ff238a4360960a8fee26d45094f92c8fefc5/theseus/Cargo.toml#L67-L69

The underlying issue is that theseus_cli depends on Tauri as of PR #951. I assume this is in error, and removing the reference to Tauri from io.rs (the following line becomes `use tokio::task::spawn_blocking;` which is what Tauri calls anyways, as far as I can tell) fixes the issue.
https://github.com/modrinth/theseus/blob/3ff0ff238a4360960a8fee26d45094f92c8fefc5/theseus/src/util/io.rs#L7

To temporarily fix this, you could add `"dep:tauri"` to the features list for `cli`. Alternatively, you can run `cargo run --bin theseus_cli` from the root theseus directory. I do not recommend checking these changes into GitHub, as they are temporary fixes for a larger issue.

As an aside, I'm not sure how the CLI builds are passing. I'm not terribly familiar with the project as a whole, but I think the Action caches the GUI build and then builds the CLI. I'd argue for clearer separation of the two - the main theseus should not depend on either theseus_gui or theseus_cli, and the CI/CD should affirm that separation. A PR which breaks that separation should more clearly fail. This is a separate issue.

As another aside, the CLI is definitely outdated. Perhaps the thing to do is to switch to [Tauri's CLI tools](https://tauri.app/v1/guides/features/cli/), which would remove the need for separate executables (but would require much more bloat for command-line users). That's a question for someone much more familiar with the project (and would, again, be a separate issue).

### For Bug 2:
This is intended behavior (I think). Since theseus has member theseus_gui, it attempts to build the GUI when you run `cargo build` from the project root. Since theseus_gui builds with `pnpm run tauri build` instead of `cargo build`, the whole thing gives an error. There is probably a way to "solve" this, but I'm not sure there's a reason to. I suppose it might be nice to build the CLI, GUI, and core all in one step.
As a general rule, `dist` should never be checked into source control. Source control (like GitHub) should hold source code and not compiled "stuff" for lack of a better word. `dist` holds that "stuff" which is why it is gitignored.

To solve this, build with `cargo build --bin theseus_cli` in the project root, or run `cargo build` in the `theseus_cli` directory instead.

**Closed** 2024-04-03 21:44 UTC
