### ISSUE TITLE
Duplicate Mod

### ISSUE THREAD

**Issue by ghost** [modrinth/code#257] opened 2023-06-24 02:31 UTC
### Describe the bug

While downloading mods I noticed that I had multiple duplicates of Fabric API, except they were all different versions of it. I assume this is why it didn't catch the duplicates, but this did, in fact, crash my game. Removing the older duplicates fixed the issue, so the problem most definitely lies in this bug.

### Steps to reproduce

I'm not certain how else to suggest this other than downloading a bunch of mods which specify different versions of Fabric API.

### Expected behavior

Presumably, the newest version should remain and the rest should go.

**Comment by triphora** [comment] 2023-06-25 17:31
Duplicate of #237

**Closed by triphora** 2023-06-25 17:31 UTC
