### ISSUE TITLE
Launcher does not detect mods in version folder (e.g `mods/1.7.10`).

### ISSUE THREAD

**Issue by e3ndr** [modrinth/code#838] opened 2023-10-25 01:40 UTC
### Describe the bug

Some mods on older versions, like Forge Microblocks, self relocate to the now-defunct version folder (e.g `mods/1.7.10`). Other mods (like Voltz) store their libraries in that folder as well. Modrinth is completely blind to any mods that sit in that folder.

### Steps to reproduce

- Use any mod that self-relocates (e.g Forge Microblocks for 1.7.10)
- Observe that Modrinth no longer lists the mod.

### Expected behavior

Modrinth should detect and list any mods that might be in that folder.

### System information

The latest version of the app on Windows.

### Additional context

While modern Forge no longer supports that folder, it was used a lot in older versions. So simply saying "don't use it!" is not an option here due to a lot of mods downloading to or self-relocating to that folder.

**Comment by Minenash** [comment] 2024-08-29 00:49
Duplicate of #672

**Closed by Minenash** 2024-08-29 00:49 UTC
Labels: bug, app
