### ISSUE TITLE
External links don't open

### ISSUE THREAD

**Issue by FelixBrakel** [modrinth/code#697] opened 2023-08-30 18:01 UTC
### Describe the bug

External links such ad the mod site, source, or patreon, but also links like opening the instance folder in the system file explorer do nothing. This is the case for both the client and the launched instance, e.g. I cannot open the resourcepack folder from minecraft.

### Steps to reproduce

1. Go to Home
2. Left-click on an instance
3. Click on Folder

### Expected behavior

The system's file explorer should be opened

### Additional context

Most likely a Linux specific issue as I know this works for someone else who is running on Windows.

I am using the provided appimage.
I think this is the 0.5.2 version? I can't find the app version in the settings.

**Comment by FelixBrakel** [comment] 2023-09-08 18:45
When I run it from the terminal I get the following error when clicking the folder button:
```
kde-open5: symbol lookup error: /usr/lib/libproxy/libpxbackend-1.0.so: undefined symbol: g_strv_builder_unref
```

I use the kde desktop environment

**Comment by triphora** [comment] 2023-12-20 05:02
Duplicate of #520

**Closed by triphora** 2023-12-20 05:02 UTC
