### ISSUE TITLE
Add a News section to the launcher.

### ISSUE THREAD

**Issue by MagmaSlime123** [modrinth/code#675] opened 2023-08-26 03:06 UTC
### Is your suggested enhancement related to a problem? Please describe.

For non-Discord users who don’t know about the Roadmap and Blog sites or Discord, they’d miss out on what’s going on with Modrinth.

### Describe the solution you'd like

Add a News section to the launcher that displays recent news/updates about Modrinth, with links to recent blog posts, Discord announcements, launcher updates, etc.

### Describe alternatives you've considered

N/A?

### Additional context

N/A.

**Comment by Felix14-v2** [comment] 2023-08-26 17:55
Please, don't repeat the fate of the official launcher with its garbage approach to the news! At least make it hideable.

**Comment by thesuzerain** [comment] 2023-08-28 15:51
Duplicate of  #259

**Closed by thesuzerain** 2023-08-28 15:51 UTC
