### ISSUE TITLE
let us create shortcuts to directly launch a profile, like how steam does

### ISSUE THREAD

**Issue by Nicodemus111** [modrinth/code#723] opened 2023-09-06 11:42 UTC
### Is your suggested enhancement related to a problem? Please describe.

it would be a bit more convenient to be able to play a profile just from the taskbar without needing to open the launcher and click play there.

### Describe the solution you'd like

i would like the ability to create shortcuts that simply launch a profile just like clicking play in the launcher window.

### Describe alternatives you've considered

i dont really think this type of improvement has alternatives.

### Additional context

the way steam lets you play a game with a shortcut is with a launch argument, for example: 
C:\Steam\steam.exe -applaunch 264710 -nosplash
would launch subnautica (my steam directory isnt the default so this would not work if you dont change it to where steam.exe is on your computer)

**Comment by moritz-t-w** [comment] 2023-11-28 18:56
#489

**Comment by Minenash** [comment] 2024-08-22 06:35
Duplicate of #489

**Closed by Minenash** 2024-08-22 06:35 UTC
Labels: enhancement, app
