### ISSUE TITLE
Broken finder dialogue opens when opening finder dialogue

### ISSUE THREAD

**Issue by isXander** [modrinth/code#962] opened 2023-12-28 11:52 UTC
### Describe the bug

When adding content from a file to an instance, two finder dialogue windows open. 
One works fine, and is brought to the front automatically. The other sits below the first, and cannot be interacted with or closed, and is stuck there until the modrinth app is closed.

### Steps to reproduce

1. Create instance
2. Add content from file
3. Observe second finder window

### Expected behavior

Only one finder window should open.

### System information

- macOS Sonoma 14.2.1
- Theseus v0.6.3 (installed via homebrew)

**Comment by triphora** [comment] 2024-01-27 06:39
Duplicate of #680

**Closed by triphora** 2024-01-27 06:39 UTC
