### ISSUE TITLE
Flathub support

### ISSUE THREAD

**Issue by Enderteck** [modrinth/code#705] opened 2023-09-01 12:20 UTC
### Is your suggested enhancement related to a problem? Please describe.

There is no package on linux exept deb. And the appimage is not well optimized and there is no .desktop file by default to launch it.

### Describe the solution you'd like

Add the app to flathub or similar website

### Describe alternatives you've considered

Package it for more distros, but it would be extremly time consuming

**Comment by thesuzerain** [comment] 2023-09-01 15:37
Duplicate of #497

**Closed by thesuzerain** 2023-09-01 15:37 UTC
