### ISSUE TITLE
game crashes on modrinth app and other launchers

### ISSUE THREAD

**Issue by Thinkseal** [modrinth/code#1316] opened 2024-07-24 17:30 UTC
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

Modrinth App v0.8.0-1 (but I also tested on v0.7.1 and it had the exact same behavior)

### What operating systems are you seeing the problem on?

Windows, MacOS

### Describe the bug

modrinth app crashes the game with a specific modpack on the latest version of quilt and does not crash on any other launcher or on fabric giving the error in the crash report of "java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.system.Library" in the crash report on macOS, it says "Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Native Library /Users/********/Library/Application Support/com.modrinth.theseus/meta/natives/1.20.1-0.26.1/liblwjgl.dylib already loaded in another classloader [
in thread "Render thread"]" and on windows it does not directly say what it's caused by ie saying "Caused by x". I tested this on Prism launcher and it didn't crash and I could get to the main menu.

log on macOS: [https://mclo.gs/LFQoCIa](https://mclo.gs/LFQoCIa)
crash report on macOS [https://mclo.gs/3WNyw1R](https://mclo.gs/3WNyw1R)
crash report on windows [https://mclo.gs/rF5d7sz](https://mclo.gs/rF5d7sz)
zipped .mrpack for the modpack in question [Yet Another Modpack 1.20.1 test 1.0.0.mrpack.zip](https://github.com/user-attachments/files/16365534/Yet.Another.Modpack.1.20.1.test.1.0.0.mrpack.zip)

### Steps to reproduce

1: unzip the modpack so it is a .mrpack file.
2: import it into modrinth.
3: try to boot the game.
4: the game should crash before getting to a visible window, but after it has launched as a separate application on the task bar.

### Expected behavior

the game boots to the main menu and will only crash once you go to load a wold (that is not intended behavior of the modpack and I know how to fix it, the crashing at world loading thing)

### Additional context

The reason I know this is a bug with the Modrinth App is that I tested on Prism launcher and it worked just fine, and I had someone else tested on the Modrinth app on windows and it crashed, which is how I got the windows crash report I got the windows crash report. I also tried reinstalling Java, repairing the instance and reinstalling liblwjgl.dylib using the latest version (3.3.3) provided on [https://www.lwjgl.org/](https://www.lwjgl.org/) and none of them worked, and according a person in [the community support channel of the Modrinth discord server](https://discord.com/channels/734077874708938864/1194455551212527696) (thegolden_knight) this may be caused by the game booting multiple times, but I cannot confirm or deny this from my testing.

**Comment by Norbiros** [comment] 2024-07-25 16:46
This problem is caused by `CorgiLib` v`4.0.1.3`. In that version they were trying to shadow jar `lwjgl`, so basically Minecraft and CorgiLib were trying to use same library which resulted in crash. This problem was fixed in v`4.0.2.0`.

**Comment by Thinkseal** [comment] 2024-07-25 16:48
Then why did it not crash on other launchers?

**Comment by Norbiros** [comment] 2024-07-25 17:35
In other launchers, LWJGL extracts .so files to subfolders in `/tmp/lwjgl_{username}` (on Linux), creating duplicate libraries like `3.3.1-4.0.1.3` and `3.3.1-build-7`. In Modrinth app this behaviour is overridden, by `"-Dorg.lwjgl.system.SharedLibraryExtractPath=${natives_directory}"` that is defined in [launcher meta](https://launcher-meta.modrinth.com/minecraft/v0/manifest.json). Modrinth gets this argument from [Mojang's launcher meta](https://piston-meta.mojang.com/v1/packages/177e49d3233cb6eac42f0495c0a48e719870c2ae/1.21.json), so I think this really is a bug in other launchers :3

**Comment by Geometrically** [comment] 2024-07-25 19:39
Closing as not an issue with the Modrinth App!

**Closed by Geometrically** 2024-07-25 19:39 UTC
