### ISSUE TITLE
Modrinth will not automatically scroll up when selecting the next page for mods. 

### ISSUE THREAD

**Issue by IREAPSOULS** [modrinth/code#353] opened 2023-07-21 15:35 UTC
### Describe the bug

explained well enough in title.

### Expected behavior

It should automatically scroll up to the top of the page instead of staying at the bottom. Possible scaling issue?

**Comment by triphora** [comment] 2023-07-21 16:13
Duplicate of #230

**Closed by triphora** 2023-07-21 16:14 UTC
