### ISSUE TITLE
Add a playtime tracker

### ISSUE THREAD

**Issue by setLore** [modrinth/code#1313] opened 2024-07-23 00:15 UTC
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate feature requests
- [X] I have checked that this feature request is not on our [roadmap](https://roadmap.modrinth.com)

### What parts of Modrinth is your feature request related too?

App

### Is your suggested feature related to a problem? Please describe.

Missing playtime tracker.

### Describe the solution you'd like

Adding a playtime tracker.

### Describe alternatives you've considered

-

### Additional context

Add a playtime tracker for each seperate instance, and maybe a total that is showed in the library tab.

**Comment by Norbiros** [comment] 2024-07-23 06:43
Duplicate of #1290

**Closed** 2024-07-23 06:50 UTC
