### ISSUE TITLE
Download button doesn't show up immediately

### ISSUE THREAD

**Issue by Gaming32** [modrinth/code#2267] opened 2024-08-23 04:20 UTC
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

Safari

### Describe the bug

After selecting a loader and version in the download prompt, the download button doesn't appear until I reopen a dropdown or reopen the popup.

### Steps to reproduce

1. Use Safari (or other Webkit browser)
2. Go go any mod
3. Click the download button
4. Choose a loader
5. Choose a Minecraft version
6. Observe that the download button doesn't appear until further interaction

### Expected behavior

The download button would appear after choosing a loader and version.

### Additional context

https://github.com/user-attachments/assets/5991eb55-bdb3-48b5-b06a-ee011ac67d48

**Comment by Minenash** [comment] 2024-08-24 17:05
Duplicate of #2203

**Closed by Minenash** 2024-08-24 17:05 UTC
Labels: website
