### ISSUE TITLE
the "x" doesnt clear the text in the search box

### ISSUE THREAD

**Issue by Kabo0Omer** [modrinth/code#277] opened 2023-06-26 15:13 UTC
### Describe the bug

the "x" doesnt clear the text in the search box

### Steps to reproduce

1 click on an instance
2 click add content
3 type anything
4 click the x to quick clear

### Expected behavior

clear the text in the box

**Comment by thesuzerain** [comment] 2023-06-29 00:00
Duplicate of #224

**Closed by thesuzerain** 2023-06-29 00:00 UTC
