### ISSUE TITLE
App doesn't start

### ISSUE THREAD

**Issue by Kokonat007** [modrinth/code#850] opened 2023-11-01 14:02 UTC
### Describe the bug

Modrinth App deosn't start

### Steps to reproduce

1. Click Modrinth App
2. Wait
3. See that i didn't boot

### Expected behavior

Start normaly

### System information

Windows 11 GhostSpectre
Freshly installed Modrinth App

### Additional context

Logs:
2023-11-01T14:45:32.605174800+01:00  INFO theseus_gui: Initialized tracing subscriber. Loading Modrinth App!
2023-11-01T14:46:32.342672800+01:00  INFO theseus_gui: Initialized tracing subscriber. Loading Modrinth App!
2023-11-01T14:47:52.246457400+01:00  INFO theseus_gui: Initialized tracing subscriber. Loading Modrinth App!
2023-11-01T14:53:47.528834600+01:00  INFO theseus_gui: Initialized tracing subscriber. Loading Modrinth App!
2023-11-01T14:54:12.773439100+01:00  INFO theseus_gui: Initialized tracing subscriber. Loading Modrinth App!
2023-11-01T14:54:43.511777200+01:00  INFO theseus_gui: Initialized tracing subscriber. Loading Modrinth App!

**Comment by theca1n** [comment] 2023-12-02 11:52
You must install microsoft edge from ghost toolbox

**Comment by wlad26** [comment] 2024-01-19 20:34
This issue should be closed as it's not a bug

**Closed** 2024-01-27 06:15 UTC

**Comment by mynameisseif** [comment] 2025-02-09 22:42
I have the same problem here; whenever I try to open the app, it just doesn't start at all.
I use the Tiny11 no sysreq version.
I have Microsoft Edge (using it to type this comment right now), and Microsoft Store is running perfectly.

What should I do?
