### ISSUE TITLE
Microsoft Login Bug

### ISSUE THREAD

**Issue by ItzAmirreza** [modrinth/code#310] opened 2023-07-03 16:37 UTC
### Describe the bug

![image](https://github.com/modrinth/theseus/assets/20891968/b90ce921-bb11-4361-aa69-d04da3123e68)

This is the error you get after login with a single-use code in your account.

### Steps to reproduce

![image](https://github.com/modrinth/theseus/assets/20891968/cec1fba8-6d3a-4c6c-90eb-dc03f5c15d4e)
![image](https://github.com/modrinth/theseus/assets/20891968/8964aadb-c86d-4769-8d98-e5e5f2feb578)
![image](https://github.com/modrinth/theseus/assets/20891968/5b5aedef-fafd-4aa9-9ebe-3ff65bb763fb)
![image](https://github.com/modrinth/theseus/assets/20891968/bf732057-dba8-4109-b832-286cbf81eefc)

### Expected behavior

To log in

**Comment by thesuzerain** [comment] 2023-07-04 16:24
Thanks for the detailed information. Does this only occur if you log in with a single use code?
(Also, I'm going to consolidate this to the #293 thread as I think its the same issue)

**Comment by thesuzerain** [comment] 2023-07-04 16:24
Duplicate of #293

**Closed by thesuzerain** 2023-07-04 16:24 UTC
