### ISSUE TITLE
Scroll Selection gets Cut Off on Version Editing Screen

### ISSUE THREAD

**Issue by DasshuCashew** [modrinth/code#308] opened 2023-07-03 01:11 UTC
### Describe the bug

Attempting to change my game version from Fabric 1.20 to 1.20.1 glitches out the selection scroll and cuts it off at the top of the  "Change Instance Versions" window. I cannot select 1.20.1 without recreating the entire instance itself, which is not hard to do, but it is still annoying. The bottom selection for 1.20 is visible yet harder to click; therefore, 1.20.1 is impossible to select.

### Steps to reproduce

- Go to your 1.20 (or earlier) instance settings,
- Select "Change Instance Versions,"
- Click the version pop-out screen,
- Attempt to select "1.20.1"

![image_2023-07-02_210949724](https://github.com/modrinth/theseus/assets/89471579/bd7f51b1-0998-4d09-be8d-0cc9659b018c)

### Expected behavior

The pop-out selection should have been in a separate window layer instead of cutting off at the edge of the "Change Instance Versions" screen.

**Comment by thesuzerain** [comment] 2023-07-04 16:16
Duplicate of #211

Thanks for the report :)

**Closed by thesuzerain** 2023-07-04 16:16 UTC

**Comment by thesuzerain** [comment] 2023-07-04 16:20
Duplicate of #211
