### ISSUE TITLE
Suggestion - Built-in server manager

### ISSUE THREAD

**Issue by faris0x** [modrinth/code#779] opened 2023-09-30 13:05 UTC
### Is your suggested enhancement related to a problem? Please describe.

I don't think it would be too difficult to add an option in the Create profile menu that allows you to choose between server and client profile. Similarly, the Modrinth [plugins tab](https://modrinth.com/plugins) could also be implemented for faster and easier installation. The server loader options can be stuff like Paper, Pufferfish, Waterfall, etc.

Thanks :D

**Comment by aftoncodes** [comment] 2023-09-30 13:06
Re: Suggestion - Built-in server manager

Something neat would also be to use the same game logs area to host the server console :P

**Comment by Treetrain1** [comment] 2023-10-23 19:14
i also would very much like something like this
i find it tedious to have to copy all the files over and manually install server files

**Comment by terminal-cs** [comment] 2023-12-22 21:06
+1 plz do this

**Comment by Minenash** [comment] 2024-08-24 17:12
Duplicate of #2157 

(I know this one is older, but the new one follows the newer template)

**Closed by Minenash** 2024-08-24 17:12 UTC
Labels: app

**Comment by StudiCraft** [comment] 2025-02-11 17:09
I want to be straight forward, it is planning this issue so the plugin tab on modrinth app does something or removing the plugin tab as we can't create servers with the modrinth app. It's an useless tab right now and does nothing special.
