### ISSUE TITLE
Unable to turn off Discord RPC

### ISSUE THREAD

**Issue by jadeposting** [modrinth/code#516] opened 2023-08-06 12:27 UTC
### Describe the solution you'd like

An option to turn off Discord RPC

**Comment by Slooshie1** [comment] 2023-08-15 23:25
I would like a toggle for Discord rich presence as well, since I use the Simple Discord RPC mod and Modrinth's rich presence overrides it

**Comment by triphora** [comment] 2023-08-23 19:31
Duplicate of #491

**Closed by triphora** 2023-08-23 19:31 UTC
