### ISSUE TITLE
Adding an unlisted modpack to Modrinth with Modrinth Modpack Management functionality

### ISSUE THREAD

**Issue by KotuMF** [modrinth/code#953] opened 2023-12-23 08:00 UTC
### Is your suggested enhancement related to a problem? Please describe.

I have a personal modpack that I made to use with friends since what I'm currently making and using is a constantly evolving modpack. It is currently Vanilla+ themed but has some mods that can make it undesirable as a pack as it adds things like flight around beacons or just really cheaty feeling items. Plus it isn't an entirely bug-free experience so I don't want to be responsible for making sure everything else works correctly for other people.

The point is, I don't want my modpack public, but I have to pass moderation and have it be able to show up in search results in order to have the modpack management functionality, which is what I want to use so my friends can easily manage the modpack without me having to walk through how to do it without wiping their settings.

### Describe the solution you'd like

Add a functionality to install unlisted modpacks via Project ID or direct link to the Library, and able to select between versions of the modpack, and update without downloading .mrpacks from external hosts and/or making new instances.

**Comment by Minenash** [comment] 2024-08-29 03:56
Duplicate of #920

**Closed by Minenash** 2024-08-29 03:56 UTC
Labels: enhancement
