### ISSUE TITLE
Duplicated window control buttons

### ISSUE THREAD

**Issue by Lorg0n** [modrinth/code#241] opened 2023-06-22 20:43 UTC
### Describe the bug

I have the window control buttons duplicated for some reason.

### Steps to reproduce

1. Updated the app

### Expected behavior

As far as I understand from the blog, the top panel should not be visible

### Additional context

OS: Windows 11 Pro
Version: 22H2 (26.03.2023)
Build: 22000.2057
![image](https://github.com/modrinth/theseus/assets/37798530/5345a40b-ee72-41cb-bb00-39ab66dae66a)

**Comment by Prospector** [comment] 2023-06-22 20:43
Duplicate of #158

**Closed by Prospector** 2023-06-22 20:43 UTC
