### ISSUE TITLE
Open instance folder button not working on Linux

### ISSUE THREAD

**Issue by Ryhon0** [modrinth/code#543] opened 2023-08-09 17:50 UTC
### Describe the bug

Clicking on the "Folder" button on the instance screen does not open the instance directory and prints this to the standard output:
```
egrep: warning: egrep is obsolescent; using grep -E
xdg-mime: no method available for querying MIME type of '/home/ryhon/.config/com.modrinth.theseus/profiles/1.20.1'
xdg-mime: mimetype argument missing
Try 'xdg-mime --help' for more information.
/tmp/.mount_modrinfNRnre/usr/bin//xdg-open: line 869: x-www-browser: command not found
/tmp/.mount_modrinfNRnre/usr/bin//xdg-open: line 869: firefox: command not found
/tmp/.mount_modrinfNRnre/usr/bin//xdg-open: line 869: iceweasel: command not found
/tmp/.mount_modrinfNRnre/usr/bin//xdg-open: line 869: seamonkey: command not found
/tmp/.mount_modrinfNRnre/usr/bin//xdg-open: line 869: mozilla: command not found
epiphany: /tmp/.mount_modrinfNRnre/usr/lib/libjson-glib-1.0.so.0: no version information available (required by /usr/lib/epiphany/libephymain.so)
epiphany: /tmp/.mount_modrinfNRnre/usr/lib/libjson-glib-1.0.so.0: no version information available (required by /usr/lib/epiphany/libephymisc.so)
epiphany: /tmp/.mount_modrinfNRnre/usr/lib/libjson-glib-1.0.so.0: no version information available (required by /usr/lib/epiphany/libephysync.so)
epiphany: /tmp/.mount_modrinfNRnre/usr/lib/libjson-glib-1.0.so.0: no version information available (required by /usr/lib/libtracker-sparql-3.0.so.0)
epiphany: symbol lookup error: /usr/lib/libgck-2.so.2: undefined symbol: g_task_set_static_name
/tmp/.mount_modrinfNRnre/usr/bin//xdg-open: line 869: konqueror: command not found
/tmp/.mount_modrinfNRnre/usr/bin//xdg-open: line 869: chromium: command not found
/tmp/.mount_modrinfNRnre/usr/bin//xdg-open: line 869: chromium-browser: command not found
/tmp/.mount_modrinfNRnre/usr/bin//xdg-open: line 869: google-chrome: command not found
/tmp/.mount_modrinfNRnre/usr/bin//xdg-open: line 869: www-browser: command not found
/tmp/.mount_modrinfNRnre/usr/bin//xdg-open: line 869: links2: command not found
/tmp/.mount_modrinfNRnre/usr/bin//xdg-open: line 869: elinks: command not found
/tmp/.mount_modrinfNRnre/usr/bin//xdg-open: line 869: links: command not found
/tmp/.mount_modrinfNRnre/usr/bin//xdg-open: line 869: lynx: command not found
/tmp/.mount_modrinfNRnre/usr/bin//xdg-open: line 869: w3m: command not found
xdg-open: no method available for opening '/home/ryhon/.config/com.modrinth.theseus/profiles/1.20.1'
```

### Steps to reproduce

1. Click on an instance
2. Press the folder button

### Expected behavior

Instance directory opens in file manager

### Additional context

Running the AppImage release on Arch Linux
App version: 0.5.0

**Comment by Parilia** [comment] 2023-08-10 09:59
Bug is present on Nobara 38 as well

**Comment by Justsnoopy30** [comment] 2023-08-14 21:57
Doesn't work on Ubuntu either

**Comment by magistermaks** [comment] 2023-10-23 12:53
This is also the case on Linux Mint (21.2 Cinnamon)
each time the instance "Folder" button is pressed the error
> nemo: symbol lookup error: /lib/x86_64-linux-gnu/libxapp.so.1: undefined symbol: g_memdup2  

is printed to the console.

I may also add that even the game itself is unable to open folders (open resourcepack folder etc) when launched with modrinth's launcher, so it's quite hard to go the instance folder

**Comment by noah-pm-dev** [comment] 2023-12-13 23:31
This also happens on Kubuntu 22.04.3 LTS, this error is printed:
```
kde-open5: symbol lookup error: /lib/x86_64-linux-gnu/libKF5GuiAddons.so.5: undefined symbol: wl_proxy_marshal_flags
```

**Comment by triphora** [comment] 2023-12-20 05:03
Duplicate of #520

**Closed by triphora** 2023-12-20 05:03 UTC
