### ISSUE TITLE
Modpack to server converter

### ISSUE THREAD

**Issue by millennIumAMbiguity** [modrinth/code#1124] opened 2024-04-16 09:16 UTC
### Is your suggested enhancement related to a problem? Please describe.

All mods already have the server/client tags. I imagine it would be possible to create a server and copy the server-side mods over.

### Describe the solution you'd like

When right-clicking a modpack in the library, get a "Create Server" option that will open a file dialog for where you want the server to be installed. (an empty folder)

![create_server](https://github.com/modrinth/theseus/assets/37588844/fd455e18-3d05-4247-892b-db6242e91395)

Then it would do the following:
1. Copy server mods.
2. Copy configs.
3. Copy additional included folders and files. _("global_packs" for example)_
4. Download and copy the server jar and/or server mod loader.
5. Show the folder.

### Describe alternatives you've considered

CurseForge supports separate server downloads.

**Comment by Minenash** [comment] 2024-08-29 06:16
Duplicate of #535

**Closed by Minenash** 2024-08-29 06:16 UTC
Labels: enhancement
