### ISSUE TITLE
Crossing off categories so projects within those categories do not appear during search

### ISSUE THREAD

**Issue by wool25** [modrinth/code#971] opened 2024-01-04 02:15 UTC
### Is your suggested enhancement related to a problem? Please describe.

Sometimes I try to find new mods but the various optimization or client-side mods clog up the results and make it harder to find mods I'd want to use

### Describe the solution you'd like

Right-clicking/double-clicking a category would cross it off and prevent projects that are in the crossed-off category from appearing

### Describe alternatives you've considered

Some mods seem to select extra categories to appear more often in searches, so some kind of user input on why a mod should be/shouldn't be in [X] category

**Comment by Minenash** [comment] 2024-08-29 04:08
Duplicate of #1871, and also has been implemented!

**Closed by Minenash** 2024-08-29 04:08 UTC
