### ISSUE TITLE
Not showing fabric mods for Quilt Instance

### ISSUE THREAD

**Issue by DovydasTEDS** [modrinth/code#1028] opened 2024-01-29 17:49 UTC
### Describe the bug

I have to override the loader to show fabric mods.

### Expected behavior

It shows the fabric mods + lets me download it.

### System information

Windows 11
Theseus v0.6.3

**Comment by wlad26** [comment] 2024-01-30 21:48
> This is tedious as I have to do it for every mod I want to update and install. It used to show fabric mods too. Quilt supports fabric mods as quilt is a fork of fabric, and works using QFAPI / QSL.

This is completely wrong, not every Fabric mod is compatible with Quilt, and also in the opposite.
You can update mods by clicking Update button, doesn't matter _what modloader you're using_

**Comment by Norbiros** [comment] 2024-07-12 16:41
Duplicate of #1188

**Comment by blryface** [comment] 2024-07-14 03:44
I think it would be more correct to say #1188 is a duplicate of #1028

**Comment by Minenash** [comment] 2024-08-29 05:04
True, but the other issue has a bit more detail and a response from the team

**Closed by Minenash** 2024-08-29 05:04 UTC
Labels: app
