### ISSUE TITLE
Going back from modpack list does not keep search parameters

### ISSUE THREAD

**Issue by GoBoopADog** [modrinth/code#1092] opened 2024-03-29 04:01 UTC
### Describe the bug

When going back from opening a mod from a modpack list, any search parameters you put in clear (Current page, mod/resource pack/shader) and you get put back to page one with no filters.

### Steps to reproduce

1. Open a modpack from your library
2. You can either add a mod filter (mod/resource pack/shader), type to search for a mod, or change the page.
3. Open any one of the mods
4. Go back with the top left button or by typing alt left
5. Witness pain

### Expected behavior

When you have an active search from a modpack and go into the mod, going back resets all search params

### System information

Windows 11 23H2
Theseus v0.6.3

### Additional context

Example from the browser menu working properly (It also works properly with a category selected):
![Modrinth_App_16REjfDfO1](https://github.com/modrinth/theseus/assets/25517283/ef08a8bb-ea2e-4776-bbab-86b79e4041e3)

Examples from the same tests but from a modpack list (1st the current page resets, 2nd the search text resets):
![Modrinth_App_pmYd87nKb0](https://github.com/modrinth/theseus/assets/25517283/5ed03599-47aa-44fa-9d8e-ffdcebce98c8)
![Modrinth_App_f7Dj2ZuEJz](https://github.com/modrinth/theseus/assets/25517283/a374cdc2-91e7-4263-be59-d51eea0b86f5)

**Comment by Minenash** [comment] 2024-08-29 06:03
Duplicate of #646

**Closed by Minenash** 2024-08-29 06:03 UTC
Labels: app
