### ISSUE TITLE
Modrinth deletes 'generated' file

### ISSUE THREAD

**Issue by EmperorCreeper** [modrinth/code#945] opened 2023-12-17 17:56 UTC
### Describe the bug

Upon trying to save a structure using structure blocks, the message "Unable to save structure" appears. I dug into the files and discovered that the 'Generated' file was deleted. I've tried this both with and without mods, and I always get the same result. I've even tried to replicate the Generated folder, but that unfortunately does not work

### Steps to reproduce

1: Get a Structure block
2: Place one Structure block down and type in 'test' 
3: Set it to 'corner'
4: Place another structure block a little away from the first one, type in 'test'
5: Set it to 'detect'
6: Click save.
7: A message will appear in chat; "Unable to save structure"

### Expected behavior

Upon clicking saving the structure, the message "Structure successfully saved" should appear. Further more, the structure file should appear in the generated file.
 

### System information

I play on Windows 11. This bug happens both with and without mods installed. I've been testing this out for about a week now. I have done some research and discovered another bug report relating to this issue, however their proposed solution does not work for me: https://github.com/modrinth/theseus/issues/857

### Additional context

![image](https://github.com/modrinth/theseus/assets/154026687/ced3601a-9d08-4484-b350-e6ffb0a6e3b3)

**Comment by EmperorCreeper** [comment] 2023-12-17 17:58
I hope this bug can be fixed soon. I am constantly importing structures through worlds to play with my friends. This is a major bug for me and it's keeping me from switching to Modrinth.

**Comment by triphora** [comment] 2024-01-27 06:44
Duplicate of #682

**Closed by triphora** 2024-01-27 06:44 UTC
