### ISSUE TITLE
Sort by Author/Add Date

### ISSUE THREAD

**Issue by POLY-021** [modrinth/code#1091] opened 2024-03-28 22:58 UTC
### Is your suggested enhancement related to a problem? Please describe.

I have an incredibly hard time pushing through debugging my modpacks as I can't keep up with the mods I have due to the sorting method in the modpack content UI. 

### Describe the solution you'd like

Adding a sorter at the top of the modpack content viewer that has multiple options could alleviate the struggle of searching for specific mods. 

Some sort options can be;
Author
Date Added

### Describe alternatives you've considered

Implementing similar ways of sorting as the "Add Content" page.

**Comment by GoBoopADog** [comment] 2024-03-29 02:18
A few pack specific sorting options would be nice as well like filtering by disabled and outdated mods in the pack, as well as automatically only showing the categories that the pack actually has.

Made a mockup of what it could look like:
![Modrinth Filter Mockup](https://github.com/modrinth/theseus/assets/25517283/d1e28d9b-58e2-4297-81af-d1610184921d)

**Comment by Minenash** [comment] 2024-08-29 06:02
Duplicate of #729 and #796

**Closed by Minenash** 2024-08-29 06:02 UTC
Labels: enhancement
