### ISSUE TITLE
In-app skin uploading functionality

### ISSUE THREAD

**Issue by qtchaos** [modrinth/code#866] opened 2023-11-09 08:05 UTC
### Is your suggested enhancement related to a problem? Please describe.

_This issue post is not really something that is urgent nor is it a problem that we should have to face anytime soon._

Having the ability to change skins within the app settings would reduce user friction when trying to upload a new skin.
### The current flow is like so:
1. User tries to change skins
2. User cannot find a way to do so
3. User joins Discord and complains
4. User has to go to minecraft.net
5. Login to minecraft.net
6. Find the section for changing the skin.
7. Finally change the skin.

### The flow I would like to see implemented:
1. User goes into settings.
2. User finds an Account section.
3. Changes their skin.

**That's 7 interactions vs 3.** Sure, this may not seem like an important feature to implement, but reducing user friction will certainly increase the likelihood that they will continue to use this launcher in favor of others. Especially since this functionality should in theory be just one [POST request to Mojang's API](https://wiki.vg/Mojang_API#Upload_Skin).

### Describe the solution you'd like

Changes to the settings page that include an Account section with a "Skin upload" section, this would have a file upload box and a skin variant select input (slim and classic).

### Describe alternatives you've considered

minecraft.net

**Comment by HaphLife** [comment] 2023-11-10 17:14
That would definitely be a good addition.

As a bare minimum/temp solution, I'd suggest they add a link to Mojang's webpage for changing skins in the launcher, so that steps 2,3, and 6 can be skipped.

**Comment by jessiejs** [comment] 2023-11-20 21:06
I believe this is a duplicate of #415

**Comment by HaphLife** [comment] 2023-11-22 05:27
> I believe this is a duplicate of #415

Yep. That definitely appears to be correct.

**Comment by Minenash** [comment] 2024-08-29 00:45
Duplicate of #415

**Closed by Minenash** 2024-08-29 00:45 UTC
Labels: enhancement
