### ISSUE TITLE
Update checker sometimes ignores new versions for certain mods

### ISSUE THREAD

**Issue by owosoup** [modrinth/code#1067] opened 2024-03-04 17:29 UTC
### Describe the bug

Sometimes, the update checker in the app doesn't show any available versions to download for a mod. When I check the mod version manually, it sometimes does have newer releases! It's not exclusive to beta or alpha releases which could be held back for a reason.

I suspect it's because I'm running fabric mods on quilt, which requires a modloader override in the content search tab. When I manually install a mod which states compatibility only with fabric, the dependencies aren't checked/downloaded either.

### Steps to reproduce

1. Have an instance with some mods
2. Click, in the mod list of the instance, a mod without updates announced.
3. Check the newest releases in <versions>.
4. Sometimes, there will be a newer release unannounced. 

### Expected behavior

Accurate update checking.

### System information

Win11 [version 10.0.22631.3155]
latest uneventful log: https://mclo.gs/iJCB4eH

**Comment by Minenash** [comment] 2024-08-29 05:49
Duplicate of #1038

**Closed by Minenash** 2024-08-29 05:49 UTC
Labels: bug
