### ISSUE TITLE
Mod updates not detcted

### ISSUE THREAD

**Issue by millennIumAMbiguity** [modrinth/code#1075] opened 2024-03-10 18:04 UTC
### Describe the bug

Update not detected. The update button claims that the latest version is used and the Update button does not update the mods.
![image](https://github.com/modrinth/theseus/assets/37588844/9765e006-3dc1-4ab6-85cb-7e21b396d949)
![image](https://github.com/modrinth/theseus/assets/37588844/a8f6022c-56c5-4df8-8a8d-08f41672bd82)

### Steps to reproduce

1. Create a mod pack (Have tested with Forge and Fabric)
2. Add an older version of any mod.
3. Try to update.

### Expected behavior

The "Update Project" button should be enabled and allow mod updating.
The Update button for selection should update selected mods.

### System information

Windows 10 64bit
theseus v0.6.3

**Comment by DzikStar** [comment] 2024-03-10 18:49
Same Issue - I can confirm.
Tried to move out and move in all mods but anyways I still don't have any update buttons. 

No clue what is happening.

**Comment by TeeJayMac** [comment] 2024-03-10 23:21
This happened a few weeks ago, it's a problem with their API that they'll probably fix soon.

**Comment by Minenash** [comment] 2024-08-29 05:51
Looks to be a duplicate of #1038

**Closed by Minenash** 2024-08-29 05:51 UTC
Labels: bug
