### ISSUE TITLE
Ctrl + Shift + V should paste a link as normal text instead of always making it into a markdown link

### ISSUE THREAD

**Issue by tildejustin** [modrinth/code#2325] opened 2024-02-08 02:04 UTC
### Is your suggested enhancement related to a problem? Please describe.

When you know how to write a markdown link, it is exceedingly frustrating to put a link where it is supposed to be only for Modrinth to automatically insert a hyperlink.
Ex.
![image](https://github.com/modrinth/code/assets/66330094/6786183f-d892-49c1-82d0-f44aea7ae08c)

### Describe the solution you'd like

The ability to bypass this by using the Shift modifier would be a nice addition.

### Describe alternatives you've considered

It could also be a toggle somewhere like the toolbar, i'm not sure where it would fit though.

**Comment by Erb3** [comment] 2024-08-28 19:37
Duplicate of #1349

**Comment by Prospector** [comment] 2024-08-28 19:38
oops yea

**Closed by Prospector** 2024-08-28 19:38 UTC
Labels: bug, web
