### ISSUE TITLE
Third party platform links in profile

### ISSUE THREAD

**Issue by Khazoda** [modrinth/code#2323] opened 2024-08-28 18:53 UTC
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate feature requests
- [X] I have checked that this feature request is not on our [roadmap](https://roadmap.modrinth.com)

### What parts of Modrinth is your feature request related too?

Website

### Is your suggested feature related to a problem? Please describe.

- It would be nice to be able to add links to social platforms (and personal websites?) on the Modrinth profile page.
- Currently the 'Bio' section does not have a markdown parser, so is just rendered as plaintext.
  - It's not possible to add links in the bio, or to even have line breaks (I believe the old site design allowed line breaks but no markdown formatting)

### Describe the solution you'd like

There are two good solutions as I see it:
1. Add markdown parsing to user's bio fields so that it's possible to add site links 🌲[like this](https://www.minecraftforum.net/forums/minecraft-java-edition/suggestions/32389-redstone-powered-retractable-spikes-as-traps-and)
2. Add a dedicated section on user's profiles for site links, along with brand icons etc.
   - The potential downside of this approach is only allowing support for certain sites with branded icons. Many mod authors may want to put their personal website links here (Favicon grabber?).

I think either implementation would work. We can already add links with markdown to project descriptions, so it seems inconsistent that it's not possible to do the same for your profile.

**Comment by Minenash** [comment] 2024-08-29 06:06
Duplicate of #2207

**Closed by Minenash** 2024-08-29 06:06 UTC
Labels: website
