### ISSUE TITLE
Every page except for modpacks won't load.

### ISSUE THREAD

**Issue by CircuitLag** [modrinth/code#321] opened 2023-07-08 22:03 UTC
### Describe the bug

On the modrinth app, when you go to the browse section, the modpacks page will load just fine, but if you try to go to another page, like mods for example, it will be stuck on a loading screen. If you press "F5" or "Ctrl R" while you are on the screen it will load.

### Steps to reproduce

Open modrinth app.
Click on the browse button on the left.
Click on any other page besides modpacks.
It will start to load forever.
Press Ctrl R or F5 and then it will load the page.

### Expected behavior

What I expected to happen is that it would load correctly.

**Comment by triphora** [comment] 2023-07-08 22:22
Duplicate of #216

**Closed by triphora** 2023-07-08 22:22 UTC
