### ISSUE TITLE
Add support for arm64 system

### ISSUE THREAD

**Issue by furax124** [modrinth/code#1291] opened 2024-07-13 11:43 UTC
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate feature requests
- [X] I have checked that this feature request is not on our [roadmap](https://roadmap.modrinth.com)

### What parts of Modrinth is your feature request related too?

App

### Is your suggested feature related to a problem? Please describe.

I use a Nintendo switch lite which is built in a tegra x1 which doesn’t support amd64 but only arm64 architecture

### Describe the solution you'd like

The modrinth app is a very cool project and it need to extend his support by adding a build support for arm64 system instead of using box64 to emulate it 

### Describe alternatives you've considered

Add a support for arm64 system

**Comment by Norbiros** [comment] 2024-07-13 11:51
Duplicate of #776

**Closed** 2024-07-13 18:38 UTC
