### ISSUE TITLE
Version selection dropdown disappeared when uploading new version.

### ISSUE THREAD

**Issue by IAFEnvoy** [modrinth/code#2343] opened 2024-08-31 06:10 UTC
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

Microsoft Edge

### Describe the bug

When try to upload aa new version, the Minecraft Version dropdown fully disappear. And it will reappear after refresh the whole page.

### Steps to reproduce

1.Open any project page and upload version.

![image](https://github.com/user-attachments/assets/692a4ccc-40e5-4e56-9201-6e2e24a857b3)

2.After you refresh page, it will appear.

![image](https://github.com/user-attachments/assets/b4f95703-37f4-4f37-9863-d24a2cd2d038)

3.But if you open a new tab and try to upload version, the dropdown still disappear.

### Expected behavior

The Minecraft Version selection dropdown should always appear.

**Comment by AnOpenSauceDev** [comment] 2024-08-31 11:26
This looks like a duplicate of #2293, but I haven't tried to upload any versions recently.

**Comment by cassiancc** [comment] 2024-08-31 19:41
I ran into the same issue earlier today running Firefox, both when uploading a new version and editing an older one.

**Closed** 2024-09-03 16:48 UTC
