### ISSUE TITLE
Modrinth unable to run on latest version of mac

### ISSUE THREAD

**Issue by markymoo2022** [modrinth/code#243] opened 2023-06-23 06:42 UTC
### Describe the bug

tried uninstalling and reinstalling several time checked updates and made sure to get everything right before launching and yet it stills says im not able to due to it not being on the "right version" of mac

**Comment by thesuzerain** [comment] 2023-06-29 00:11
Which version of mac is this? Can you provide a screenshot of the error message that it provides? Thanks

**Comment by Geometrically** [comment] 2023-07-28 20:05
not enough info/duplicate of mojave issue?

**Closed by Geometrically** 2023-07-28 20:05 UTC
