### ISSUE TITLE
Modrinth App Icon Issue

### ISSUE THREAD

**Issue by tobelious** [modrinth/code#309] opened 2023-07-03 05:41 UTC
### Describe the bug

In attempt to set an icon for a mod profile, the launcher's navigation tabs, loading in general, and more ultimately just stop working in random ways.

### Steps to reproduce

1. Go to any mod profile
2. Go to Option then set an icon
3. Attempt to to anything else and you'll realize certain tabs are broken, etc.
Restarting the launcher is the only way to fix the broken things

### Expected behavior

Expected for an icon to be set

### Additional context

More context can be provided

**Comment by TheMaster223** [comment] 2023-07-03 05:42
What I provided is quite vague so I can provide further context if needed

**Comment by thesuzerain** [comment] 2023-07-04 16:19
Yup, I think you found the same issue! Thanks for the report!

Duplicate of #212

**Comment by thesuzerain** [comment] 2023-07-04 16:19
Duplicate of #212 

Yup, I think you found the same issue. Thanks for the report!

**Closed by thesuzerain** 2023-07-04 16:19 UTC

**Comment by thesuzerain** [comment] 2023-07-04 16:20
Duplicate of #211
