### ISSUE TITLE
Mc server creator in Modrinth launcher

### ISSUE THREAD

**Issue by gryhfgyd** [modrinth/code#1239] opened 2024-06-25 06:28 UTC
### Describe the solution you'd like

@734078150967033969
I have an idea for a new feature in modrinth launcher, add creating minecraft servers directly in the launcher (locally). And there you can download datapacks and plugins or mods (as well as kernels) from resources such as bukkit, spigot, paper hangar. I think this is a good idea and I think one of the modrinth developers will see it:)

**Comment by blryface** [comment] 2024-06-25 10:17
It could be nice in a separate tool by modrinth, but I don't really see why they'd include it in the main app, that could cause confusion to lesser experienced users thinking it's another modloader

**Comment by Gaming32** [comment] 2024-06-26 18:09
If it's put by the mod loader, it would look like that, yeah. What I think would be best though, is to have the + button open a little menu where you can choose between client instance and server. Some other launchers do also have this feature, such as ATLauncher.

**Comment by Norbiros** [comment] 2024-08-22 18:41
Duplicates #779

**Comment by Minenash** [comment] 2024-08-24 17:11
Duplicate of #2157 

(I know this one is older, but the new one follows the newer template)

**Closed by Minenash** 2024-08-24 17:11 UTC
Labels: enhancement
