### ISSUE TITLE
cant rezise app in top bar

### ISSUE THREAD

**Issue by Schweeeeeeeeeeeeeeee** [modrinth/code#2239] opened 2024-08-22 04:44 UTC
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

8.1

### Describe the bug

Only 5% or so of the top bar can be used to resize it drags the window instead of resizing it

https://github.com/user-attachments/assets/50f51bf5-918b-4a4c-97da-44aeb3d5e5bc

### Steps to reproduce

open the app and thy resizing at the top bar

**Comment by Minenash** [comment] 2024-08-29 05:52
Duplicate of #372

**Closed by Minenash** 2024-08-29 05:52 UTC
Labels: bug, app
