### ISSUE TITLE
Packs imported from prismlauncher originating from curseforge are broken

### ISSUE THREAD

**Issue by vortivoid** [modrinth/code#942] opened 2023-12-16 19:02 UTC
### Describe the bug

If you download a curseforge modpack on prismlauncher then import it as a profile on the modrinth app, the profile becomes rather broken in that you can't edit the mods as it treats it as a locked pack. However there is no option to unlink the pack anywhere, nor is there any way to add content as the button is replaced with an "update modpack" button which doesnt show anything to update to.

### Steps to reproduce

1. download any curseforge modpack on prismlauncher
2. in the modrinth app select create profile > import from launcher, then select prismlauncher and import the pack
3. try to edit the instance and see the issue described above

### Expected behavior

instance would simply be treated as a regular one, not anything linked to a modpack, curseforge or otherwise.

### System information

Windows 10
Theseus v0.6.3

### Additional context

![image](https://github.com/modrinth/theseus/assets/53712490/333fbbd9-8059-4609-b117-5d3e07383388)
![image](https://github.com/modrinth/theseus/assets/53712490/bc8d2423-6775-40a8-b21a-99820a551caa)
![image](https://github.com/modrinth/theseus/assets/53712490/7fdd444e-4dc8-4e75-a013-f0675345a714)

**Comment by triphora** [comment] 2024-01-27 06:41
Duplicate of #814

**Closed by triphora** 2024-01-27 06:41 UTC
