### ISSUE TITLE
add a option to use your dGPU

### ISSUE THREAD

**Issue by Parilia** [modrinth/code#555] opened 2023-08-10 14:34 UTC
### Is your suggested enhancement related to a problem? Please describe.

Trying to get you dGPU to run minecraft in linux is very annoying and can be confusing

### Describe the solution you'd like

Add an option to run using the dGPU, prism has this option for reference. 

### Describe alternatives you've considered

the alternative is:
 AMD dGPU, launch the game with DRI_PRIME=1 infront of it.
NVIDIA dGPU, https://download.nvidia.com/XFree86/Linux-x86_64/435.17/README/primerenderoffload.html
NV_PRIME_RENDER_OFFLOAD=1 GLX_VENDOR_LIBRARY_NAME=nvidia SOME-GAME-COMMAND

As for where to put it and if it actually works, thats way to complex for a lot of users

**Comment by Minenash** [comment] 2024-08-22 06:07
Duplicate of #303

**Closed by Minenash** 2024-08-22 06:07 UTC
Labels: app
