### ISSUE TITLE
[improvement] Uninstall mods from the content browser

### ISSUE THREAD

**Issue by CarbonGhost** [modrinth/code#1066] opened 2024-03-04 04:35 UTC
### Is your suggested enhancement related to a problem? Please describe.

It's easy to install mods from the content browser, but to uninstall one I must return to the instance view. This is not ideal UX.

### Describe the solution you'd like

Replace the disabled "Installed" button with a button to uninstall the mod as indicated below:

![image](https://github.com/modrinth/theseus/assets/39361743/688c1776-6040-412e-82e9-c5a95d6b41ed)

Or some equivalent.

### Describe alternatives you've considered

Just depends on how the UI should look.

**Comment by Minenash** [comment] 2024-08-29 05:47
Duplicate of #424

**Closed by Minenash** 2024-08-29 05:47 UTC
Labels: enhancement
