### ISSUE TITLE
UI Scale

### ISSUE THREAD

**Issue by redpenguinyt** [modrinth/code#1141] opened 2024-04-24 16:28 UTC
### Is your suggested enhancement related to a problem? Please describe.

With the most recent update (On Hyprland/Wayland) the launcher is now too small. 

### Describe the solution you'd like

It would be nice to be able to control the UI scale in-app using a keybind and setting, equivalent to `Ctrl +` and `Ctrl -` in browsers and web apps such as Electron-based applications

**Comment by Norbiros** [comment] 2024-07-10 14:42
Duplicate of #214

**Closed** 2024-07-14 11:06 UTC
Labels: enhancement
