### ISSUE TITLE
Hover text doesn't go away in linux

### ISSUE THREAD

**Issue by NotMurPh** [modrinth/code#950] opened 2023-12-19 11:41 UTC
### Describe the bug

hi , me and my friend tested this on arch linux using dwm and bspwm window managers we installed modrinth-app and modrinth-app-bin from yay and the problem is that when you hover something in the app the text that shows up never goes away its kinda inconsistent and sometimes you can make it go away by hovering again or sometimes it just works 

here is a picture showcasing the problem : 
![image](https://github.com/modrinth/theseus/assets/66315425/f9bce9cb-cd1f-47eb-917c-0d0d4e3262ab)

### Steps to reproduce

1. open the app 
2. go to another menu for example browse menu
3. hover something like the home button 

### Expected behavior

hover texts should go away after you stop hovering

### System information

OS: Arch Linux
KERNEL: 6.6.7-arch1-1
CPU: 13th Gen Intel Core i5-13600KF
GPU: NVIDIA GeForce RTX 3070 Ti
GPU DRIVER: NVIDIA 545.29.06
RAM: 16 GB

app version : local/modrinth-app-bin 0.6.3-1

my whole system configuration although modrinth isn't still in there : 
https://github.com/NotMurPh/DotFiles

### Additional context

btw thank you for the awesome client and caring about linux community :)

**Comment by triphora** [comment] 2024-01-27 06:43
Duplicate of #829

**Closed by triphora** 2024-01-27 06:43 UTC
