### ISSUE TITLE
Exporting modpacks isn't very "CORRECT"

### ISSUE THREAD

**Issue by Rocksy7** [modrinth/code#1081] opened 2024-03-17 00:25 UTC
### Describe the bug

![image](https://github.com/modrinth/theseus/assets/154062217/6d098c5b-0e10-4e7a-9eae-115059f7d448)
![image](https://github.com/modrinth/theseus/assets/154062217/f133d0c4-58da-4c93-99c5-2f957a1f9715)
You should be able to tell the issue. wasn't an issue months ago.
 

### Steps to reproduce

export
extract in filesystem
open
read

### Expected behavior

"server": "optional" or "none",

### Additional context

If somehow you missed the whole context of the issue. The mod is meant for the client only yet appears as required in the json file.

**Comment by TheKodeToad** [comment] 2024-03-19 01:17
Mods which are marked as server probably shouldn't be marked as unsupported on the client - they usually have an effect in singleplayer. However, client side mods should virtually never be installed on the server unless I'm missing something.

As indicated in code comments it seems you will eventually be able to customise each file! But IMO the defaults should only be marking as unsupported on the server if it mod is marked as "client" and not the other way around.

**Comment by JulianVennen** [comment] 2024-04-25 11:24
This seems to be a duplicate of #911

**Comment by Minenash** [comment] 2024-08-29 05:57
Duplicate of #911

**Closed by Minenash** 2024-08-29 05:57 UTC
