### ISSUE TITLE
Window frame unresponsive on edges

### ISSUE THREAD

**Issue by ghost** [modrinth/code#887] opened 2023-11-19 10:27 UTC
### Describe the bug

The buttons on the custom window frame don't work if you click near the very edge of the window.

### Steps to reproduce

1. Open the app
2. Maximize the app's window
3. Move the cursor to the top right corner of the screen
4. Click
5. The close button animates, but nothing happens.

### Expected behavior

The window frame buttons work no matter where you click them

### System information

Windows 10, App 0.6.1

**Comment by Felix14-v2** [comment] 2023-11-19 18:51
Duplicates https://github.com/modrinth/theseus/issues/639 I guess

**Comment by triphora** [comment] 2024-01-27 06:35
Duplicate of #377

**Closed by triphora** 2024-01-27 06:35 UTC
