### ISSUE TITLE
Button to Clone Profile

### ISSUE THREAD

**Issue by JaegyuDev** [modrinth/code#718] opened 2023-09-04 06:39 UTC
### Is your suggested enhancement related to a problem? Please describe.

Having to open the profiles folder and copy/paste contents to clone a profile can be tedious.

### Describe the solution you'd like

Having the option to clone the profile in right click menu in the Library page would be helpful.

### Describe alternatives you've considered

You could also have an option to do it within the Profile page, and within its settings, but both would feel more hidden.

**Comment by Poopooracoocoo** [comment] 2023-09-04 10:20
#229

**Comment by thesuzerain** [comment] 2023-09-05 16:53
Duplicate of #229

**Closed by thesuzerain** 2023-09-05 16:53 UTC
