### ISSUE TITLE
Better colors for analytics charts

### ISSUE THREAD

**Issue by srnyx** [modrinth/code#2987] opened 2024-12-06 20:00 UTC
### Please confirm the following.

- [x] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate feature requests
- [x] I have checked that this feature request is not on our [roadmap](https://roadmap.modrinth.com)

### Is your suggested feature related to a problem? Please describe.

It's extremely difficult to see this thin line for my analytics for one of my projects
![Image](https://github.com/user-attachments/assets/899be9a9-91bf-4179-95de-2c5a5b13758a)

### Describe the solution you'd like

A brighter color for the line

### Describe alternatives you've considered

Squinting my eyes, getting closer to my screen, getting my eyes checked, etc...

### Additional context

So far only noticed it with one of my projects: https://modrinth.com/plugin/personal-phantoms/settings/analytics

**Comment by Prospector** [comment] 2024-12-06 20:27
You can click the color button in the top right to switch to a non-project-specific palette that should be easy to read.

**Comment by Prospector** [comment] 2024-12-06 20:27
Duplicate of #1456

**Closed by Prospector** 2024-12-06 20:27 UTC
